### GET all cash-cards
GET http://localhost:8080/cash-cards

### Basic auth [base64-encoded-string]
GET http://localhost:8080/cash-cards
Authorization: Basic dXNlcjowMDQ3ZGFiNS05MDE3LTRjNjctODM5Zi1hYTM0MGZlNDg4MDE=

### Bearer auth
GET http://localhost:8080/cash-cards
Authorization: Bearer eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJzYXJhaDEiLCJhdWQiOiJodHRwczovL2Nhc2hjYXJkLmV4YW1wbGUub3JnIiwiaXNzIjoiaHR0cHM6Ly9pc3N1ZXIuZXhhbXBsZS5vcmciLCJleHAiOjE3OTg3ODA3OTksImlhdCI6MTUxNjIzOTAyMiwic2NwIjpbImNhc2hjYXJkOnJlYWQiLCJjYXNoY2FyZDp3cml0ZSJdfQ.qma3O-23ghqddShO5-9B3SSFP0e0F6QM8ZdhwFGhNEiE370Ob2M3z-DMW-YsFbkZ7XGCafL8mk37_zCJBkOathyStTIeOV1LTiJgBTvCGgaE8aXoG5rsBF5E8xkGv6QGNnWB9J-a-1m_v5aSU_ggBOkxoQAIZO9nqngrHviyxwXZDdCD3RJ7Ee9UEJskgR-1Z7Fq8lV-n9rnM9SIB0fSBqGnauAPnGmcOpaliCLr6VpRAEKIRQr3c-8FiN0hIClJu9E63atyf_s0PEffet4GC_p_-keo23VmS5RgR5eQMkdDuoJVXne_YLxLBrcZgN5pfkWS5exbX7f-zwsYzxhL8g

###
POST http://localhost:8080/cash-cards
Authorization: Basic dXNlcjowMDQ3ZGFiNS05MDE3LTRjNjctODM5Zi1hYTM0MGZlNDg4MDE=
Content-Type: application/json

{
  "owner": "sarah1",
  "id": 102,
  "amount": 100
}
